services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: ${WWWUSER:-1000}
        WWWGROUP: ${WWWGROUP:-1000}
    container_name: roomly_app
    volumes:
      - ./:/var/www
    environment:
      - WWWUSER=${WWWUSER:-1000}
      - WWWGROUP=${WWWGROUP:-1000}
    networks:
      - roomly

  nginx:
    image: nginx:alpine
    container_name: roomly_nginx
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - roomly

  db:
    image: postgres:15.12-alpine3.21
    container_name: roomly_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - roomly

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: roomly_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - db
    networks:
      - roomly

  mailpit:
    image: axllent/mailpit
    container_name: roomly_mailpit
    ports:
      - "${MAILPIT_PORT:-8025}:8025"
    networks:
      - roomly

volumes:
  dbdata:

networks:
  roomly:
    driver: bridge

